version: 0.2

env:
    git-credential-helper: yes
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven git
      - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      - apt-get install git-lfs
      - ls -latrh 
      - git lfs fetch
      - git lfs pull
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo Finishing pre-build setup
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
    finally:
      - echo Finishing build phase
  post_build:
    commands:
      - echo Entered the post_build phase...
      - ls -latrh 
      - cat .gitattributes
      - echo Build completed on `date`
